// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7ti7ygLWVb8FFOZEtaLUbBcFjaJsk-g',
    appId: '1:586416401938:web:a974e0cd47e5ab9af9f2cb',
    messagingSenderId: '586416401938',
    projectId: 'chat-740ab',
    authDomain: 'chat-740ab.firebaseapp.com',
    storageBucket: 'chat-740ab.appspot.com',
    measurementId: 'G-F7S80P68CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACD1m66pGZygJ0tbWBAuqfEWZ8_Tg9G9U',
    appId: '1:586416401938:android:fc5ffba61e22fabdf9f2cb',
    messagingSenderId: '586416401938',
    projectId: 'chat-740ab',
    storageBucket: 'chat-740ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdwMiX5b2T6Y5L6bQ9Huw9HZLjz3uX5gE',
    appId: '1:586416401938:ios:c2b4ded3762d3e1bf9f2cb',
    messagingSenderId: '586416401938',
    projectId: 'chat-740ab',
    storageBucket: 'chat-740ab.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdwMiX5b2T6Y5L6bQ9Huw9HZLjz3uX5gE',
    appId: '1:586416401938:ios:5d583763e425d16cf9f2cb',
    messagingSenderId: '586416401938',
    projectId: 'chat-740ab',
    storageBucket: 'chat-740ab.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
